### ISSUE TITLE
guide-extension support for Neo4j 3.0.1

### ISSUE THREAD

**Issue by dhimmel** [jexp/neo4j-guides#2]
Does the `guide-extension` plugin need any updates to work in Neo4j 3.0.1? Or should I be able to follow the instructions in the [current README](https://github.com/jexp/neo4j-guides/blob/f8123837c14ebc4ca3d9426caa55feae378f6e6a/guide-extension/readme.adoc) and use the jar created for 2.3.2 ([download](https://dl.dropboxusercontent.com/u/14493611/neo4j-guide-extension-2.3.2.jar))?

Also do you anticipate that this extension will continue to be supported for future Neo4j versions? I'm [choosing which method](https://github.com/neo4j/neo4j-browser/issues/170#issuecomment-221963126) to use for hosting a style and a large number of guides. It would be nice to use guide-extension so as not to violate the same-origin policy. However, if the best longterm solution is to get CORS working, then that could influence my decision.

**Comment by jexp** [comment]
I would host it on a dedicated server or s3 bucket this was meant for small demos.

I updated it to 3.0.1 though, there were no API changes needed.

**Comment by dhimmel** [comment]
> I updated it to 3.0.1 though, there were no API changes needed.

Awesome thanks.

> I would host it on a dedicated server or s3 bucket this was meant for small demos.

Currently, http://neo4j.het.io/ is hosted in a 2-core/2-GB-memory droplet in the DigitalOcean. I've been [using Docker](https://github.com/dhimmel/hetionet/tree/383152be2c07f8f5427dd7069535c82b0c5e8d85/hetnet/neo4j/docker) to make the process easier. Still a work in progress, and this is the first time I've used these technologies so lots of learning.
