### ISSUE TITLE
Where should the resources/webapp directory for the guide-extension reside?

### ISSUE THREAD

**Issue by dhimmel** [jexp/neo4j-guides#4]
I read that:

> The `StaticWebResource` provides the web-files of the visualization from the `resources/webapp` directory.

So where exactly is the `resources/webapp` directory relative to? Should `resources` be created in a `graph.db` directory or in the main neo4j directory alongside `plugins` and `conf`?

**Comment by dhimmel** [comment]
I'm assuming that `org.neo4j.server.guide.directory=data/guides` in `conf/neo4j.conf` sets the location for guides to `data/guides` rather than `resources/webapp`.

However, if I put the HTML guides in `data/guides` (alongside `data/databases`), I still get a blank page when requesting a guide by URL. Since I'm using the [Neo4j 3.0.1 Community Docker](https://github.com/neo4j/docker-neo4j/blob/78cb77fe5be9041434d7f5ba4d3b12209904dbfa/3.0.1/Dockerfile), the full path is `/var/lib/neo4j/data/guides/`.

**Comment by jexp** [comment]
You don't have to concern yourself with `resources/webapp` that's for content the embedded webapp would need.

`org.neo4j.server.guide.directory=data/guides` this should just be what it says.
