### ISSUE TITLE
guide-extension plugin and Neo4j 3.0: guides fail to load

### ISSUE THREAD

**Issue by dhimmel** [jexp/neo4j-guides#5]
I performed the following steps to configure the guide-extension (tried both 3.0.1 and 3.0.2 Community):

1. Move `neo4j-guide-extension-3.0.1.jar` to the `plugins` directory.

2. In `conf/neo4j.conf` apply the following settings:

  ```
  dbms.security.auth_enabled=false
  org.neo4j.server.thirdparty_jaxrs_classes=extension.web=/guides
  org.neo4j.server.guide.directory=data/guides
  ```

3. Create a `data/guides` directory and add a guide I made for testing (`clofarabine-MS.html`).

4. Start or restart the Neo4j instance.

When I enter a guide URL in my web browser, I get the following error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:7474/guides/clofarabine-MS.html 
```

Any ideas? Is there a way to troubleshoot plugins? Can I see whether the plugin is starting up and doing anything?

**Comment by jexp** [comment]
Wrong config name it changed with 3.0

Von meinem iPhone gesendet

**Comment by dhimmel** [comment]
> Wrong config name it changed with 3.0

Can you be more specific? Thanks!

**Comment by jexp** [comment]
the configuration name changed to : `dbms.unmanaged_extension_classes`

**Comment by dhimmel** [comment]
Okay changing the configuration line from:

```
org.neo4j.server.thirdparty_jaxrs_classes=extension.web=/guides
```

to:

```
dbms.unmanaged_extension_classes=extension.web=/guides
```

resulted in my guides loading. Here's the doc for [`dbms.unmanaged_extension_classes`](http://neo4j.com/docs/operations-manual/3.0/#config_dbms.unmanaged_extension_classes) in Neo4j 3.0.

@jexp updated the guide-extension documentation in 8d642691221162c079af6fce08483bfe10a108cc, so I'll close the issue.
